### ISSUE TITLE
채점 서버를 설계한다

### ISSUE THREAD

**Issue by reddevilmidzy** [aubergine-dance/backend#7]
### 🍆 Description
- Polygon의 문제인 잦은 지연과 낮은 가용성을 보안하기 위해 채점 서버를 어떻게 구현할 지 고민한다.
- 어떤 기술 스택을 가져가야 할 지도 고민 지점이다.

**Comment by reddevilmidzy** [comment]
### 🌽 
- 처리 속도, 효율성을 고려하고 구글링하였을 때 Rust와 Go로 범위가 좁혀졌다. 
- 순수 연산 성능은 Go보다는 Rust가 조금 더 뛰어나다고 한다.
- 하지만 Rust는 러닝 커브가 높아 현재 빠르게 구현하기는 어려울 것 같아 생산성 높은 Go를 선택하고자 한다.

![image](https://github.com/user-attachments/assets/42dbf2c6-5ad7-4daa-83f5-51d281be2e25)


---
참고

* [Golang vs Rust 퍼포먼스 벤치마킹 썰](https://blog.stibee.com/golang-vs-rust-peopomeonseu-bencimaking-sseol/)
* [십년지기 언어, 러스트와 고(Go)](https://yozm.wishket.com/magazine/detail/1040/)
* [Rust vs Go in 2024](https://bitfieldconsulting.com/posts/rust-vs-go)

**Comment by donghoony** [comment]
채점 서버는 [이쪽](https://github.com/aubergine-dance/think/issues)에서 이야기할게용 (관심사 분리)
